### ISSUE TITLE
Comma-separated selectors

### ISSUE THREAD

**Issue by cyouh95** [Elv1610/prj-rev-bwfs-dasmoto#2]
You could use comma-separated selectors to specify shared properties among multiple elements:

```css
h1, h2, .prices {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/Elv1610/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/style.css
